language: haskell

before_install:
      ## Emacs
      - sudo add-apt-repository -y ppa:cassou/emacs
      - sudo apt-get update -qq
      - sudo apt-get -f install
      - sudo apt-get install -qq emacs24 emacs24-el

      ## Idris prereqs
      - sudo add-apt-repository --yes ppa:h-rayflood/llvm
      - sudo apt-get update -qq
      - sudo apt-get install -qq libgc-dev llvm-3.3
      - sudo apt-get install -qq libghc-unordered-containers-dev libghc-mtl-dev libghc-network-dev libghc-xml-dev libghc-transformers-dev libghc-text-dev libghc-utf8-string-dev libghc-vector-dev libghc-split-dev libghc-ansi-terminal-dev libghc-ansi-wl-pprint-dev
      # trifecta dependencies
      - sudo apt-get install -qq libghc-blaze-builder-dev libghc-blaze-html-dev libghc-bifunctors-dev libghc-hashable-dev libghc-semigroups-dev libghc-semigroupoids-dev libghc-parallel-dev libghc-comonad-dev libghc-terminfo-dev libghc-keys-dev
      # Haddock dependencies
      - sudo apt-get install hscolour
      # test dependency
      - sudo apt-get install -qq expect


# Install Idris
install:
      - pushd .
      - git clone https://github.com/idris-lang/Idris-dev.git /tmp/Idris-dev
      - cd /tmp/Idris-dev
      - cabal install -f FFI -f LLVM --only-dependencies --enable-tests
      - cabal configure -f FFI -f LLVM
      - cabal sdist
      - cd ..
      - tar -xf Idris-dev/dist/idris*.tar.gz
      - cd idris*
      - cabal configure -f FFI -f LLVM
      - cabal build
      - cabal copy

before_script: true

script:
      - popd
      - make build
      - make test